/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apps;


import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shiva
 */
public class MemberWindow extends javax.swing.JFrame {

    /**
     * Creates new form MemberWindow
     */
    public MemberWindow() {
        initComponents();
    }
    
    String ac_no;
    public MemberWindow(String ac_no) {
        initComponents();
        this.ac_no = ac_no;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        DepositWithdrawl = new javax.swing.JInternalFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        withimg = new javax.swing.JLabel();
        transferfund = new javax.swing.JInternalFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        transimg = new javax.swing.JLabel();
        fastcashwith = new javax.swing.JInternalFrame();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        fastimg = new javax.swing.JLabel();
        balanceEnquiry = new javax.swing.JInternalFrame();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        balimg = new javax.swing.JLabel();
        ministmt = new javax.swing.JInternalFrame();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField12 = new javax.swing.JTextField();
        ministmtimg = new javax.swing.JLabel();
        mobreg = new javax.swing.JInternalFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        bgmob = new javax.swing.JLabel();
        pinchange = new javax.swing.JInternalFrame();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        jTextField11 = new javax.swing.JTextField();
        jPasswordField6 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        pinimg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jToolBar1.setRollover(true);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.gif"))); // NOI18N
        jButton12.setToolTipText("deposit or withdrawl");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/btn-refresh.jpg"))); // NOI18N
        jButton13.setToolTipText("Fast Cash Withdrawl");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buy-back-shares-300x300.jpg"))); // NOI18N
        jButton14.setToolTipText("Transfer Fund");
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/6.png"))); // NOI18N
        jButton15.setToolTipText("Balance Enquiry");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/voice_of_user3.jpg"))); // NOI18N
        jButton16.setToolTipText("Mini StateMent");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Create-a-new-file-1127140127.png"))); // NOI18N
        jButton17.setToolTipText("Mobile Registration");
        jButton17.setFocusable(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton17);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/arrow.jpg"))); // NOI18N
        jButton19.setToolTipText("Pin Change");
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton19);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/8.png"))); // NOI18N
        jButton18.setToolTipText("Logout");
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton18);

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DepositWithdrawl.setBackground(new java.awt.Color(255, 153, 153));
        DepositWithdrawl.setClosable(true);
        DepositWithdrawl.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        DepositWithdrawl.setTitle("Depositwithdrawl");
        DepositWithdrawl.setVisible(false);
        DepositWithdrawl.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Enter Account Number");
        DepositWithdrawl.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Enter Amount");
        DepositWithdrawl.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Type Of Account");
        DepositWithdrawl.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        DepositWithdrawl.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 250, -1));
        DepositWithdrawl.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 250, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        DepositWithdrawl.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 250, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        DepositWithdrawl.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 140, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Withdrawl");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        DepositWithdrawl.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 130, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Deposit/Withdrawl:");
        DepositWithdrawl.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 390, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        DepositWithdrawl.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 120, 60));

        withimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk2.jpg"))); // NOI18N
        DepositWithdrawl.getContentPane().add(withimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));

        jDesktopPane1.add(DepositWithdrawl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        transferfund.setBackground(new java.awt.Color(51, 255, 255));
        transferfund.setClosable(true);
        transferfund.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        transferfund.setTitle("Transfer Amount");
        transferfund.setPreferredSize(new java.awt.Dimension(0, 0));
        transferfund.setVisible(false);
        transferfund.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel15.setText("Transfer Amount");
        transferfund.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 460, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Enter Account Number");
        transferfund.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Enter IFSC code");
        transferfund.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Enter Amount");
        transferfund.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 29));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Confirm Amount");
        transferfund.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 33));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Enter Pin");
        transferfund.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        transferfund.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 231, -1));
        transferfund.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 231, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        transferfund.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 231, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        transferfund.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 231, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        transferfund.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 231, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Submit");
        transferfund.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 121, 60));

        jButton5.setBackground(new java.awt.Color(204, 0, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Cancel");
        transferfund.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 129, 60));

        transimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk13.jpg"))); // NOI18N
        transimg.setMinimumSize(new java.awt.Dimension(600, 555));
        transferfund.getContentPane().add(transimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 510));

        jDesktopPane1.add(transferfund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));

        fastcashwith.setBackground(new java.awt.Color(102, 255, 255));
        fastcashwith.setClosable(true);
        fastcashwith.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        fastcashwith.setTitle("Fast Transaction");
        fastcashwith.setVisible(false);
        fastcashwith.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel21.setText("Fast Cash Withdrawl");
        fastcashwith.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 520, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Enter Amount ");
        fastcashwith.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Enter Pin Number");
        fastcashwith.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, 26));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("the amount must be below 5000 can only deducted by fast cash withdrawl");
        fastcashwith.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 583, -1));
        fastcashwith.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 185, -1));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        fastcashwith.getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 185, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setText("NOTE:");
        fastcashwith.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 76, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("WithDraw");
        fastcashwith.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 159, 50));

        fastimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk2.jpg"))); // NOI18N
        fastcashwith.getContentPane().add(fastimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 730));

        jDesktopPane1.add(fastcashwith, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        balanceEnquiry.setBackground(new java.awt.Color(51, 255, 255));
        balanceEnquiry.setClosable(true);
        balanceEnquiry.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        balanceEnquiry.setTitle("Balance Enquiry");
        balanceEnquiry.setVisible(false);
        balanceEnquiry.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(0, 153, 51));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setText("Check Balance");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        balanceEnquiry.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel28.setText("Your Current Amount is :");
        balanceEnquiry.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 209, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        balanceEnquiry.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 236, 40));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel37.setText("Balance Enquiry");
        balanceEnquiry.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 382, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Account Number");
        balanceEnquiry.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        balanceEnquiry.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 320, -1));

        balimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk16.jpg"))); // NOI18N
        balanceEnquiry.getContentPane().add(balimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jDesktopPane1.add(balanceEnquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        ministmt.setClosable(true);
        ministmt.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ministmt.setTitle("Mini Statement");
        ministmt.setEnabled(false);
        ministmt.setFocusCycleRoot(false);
        ministmt.setMinimumSize(new java.awt.Dimension(400, 500));
        ministmt.setVisible(false);
        ministmt.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setText("Mini StateMent");
        ministmt.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("Account Number");
        ministmt.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 220, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 204));
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        ministmt.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 150, 44));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(35);
        jTable1.setRowMargin(5);
        jScrollPane1.setViewportView(jTable1);

        ministmt.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 864, 430));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ministmt.getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 261, -1));

        ministmtimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk13.jpg"))); // NOI18N
        ministmt.getContentPane().add(ministmtimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 680));

        jDesktopPane1.add(ministmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        mobreg.setBackground(new java.awt.Color(51, 255, 255));
        mobreg.setClosable(true);
        mobreg.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        mobreg.setTitle("Mobile registration");
        mobreg.setToolTipText("");
        mobreg.setVisible(false);
        mobreg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("Mobile Registration");
        mobreg.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 396, 70));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 240, 240));
        jLabel32.setText("Enter New Mobile Number");
        mobreg.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));
        mobreg.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 280, -1));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        mobreg.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 135, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Account Number");
        mobreg.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        mobreg.getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 280, -1));

        bgmob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk12.jpg"))); // NOI18N
        mobreg.getContentPane().add(bgmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        jDesktopPane1.add(mobreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));

        pinchange.setBackground(new java.awt.Color(51, 255, 255));
        pinchange.setClosable(true);
        pinchange.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        pinchange.setTitle("Pin Change");
        pinchange.setVisible(false);
        pinchange.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel33.setText("Pin Change");
        pinchange.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setText("Enter Old Pin");
        pinchange.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setText("Enter New Pin");
        pinchange.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setText("Confirm New Pin ");
        pinchange.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));
        pinchange.getContentPane().add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 242, -1));
        pinchange.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 242, -1));
        pinchange.getContentPane().add(jPasswordField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 242, -1));

        jButton10.setBackground(new java.awt.Color(0, 153, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("Change");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pinchange.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 140, 50));

        jButton11.setBackground(new java.awt.Color(204, 0, 51));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton11.setText("Cancel");
        pinchange.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 140, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Account Number");
        pinchange.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        pinchange.getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 240, -1));

        pinimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bkk2.jpg"))); // NOI18N
        pinchange.getContentPane().add(pinimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 580));

        jDesktopPane1.add(pinchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jMenu2.setBackground(new java.awt.Color(102, 102, 102));
        jMenu2.setText("transactions");

        jMenuItem1.setText("Cash Depositwithdrawl");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setText("Fast Cash Withdrawl");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Transfer Fund");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(102, 102, 102));
        jMenu3.setText("Enquiry");

        jMenuItem5.setText("Balance Enquiry");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Mini StateMent");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(204, 204, 204));
        jMenu4.setText("Mobile Registration");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Mobile Registration");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(204, 204, 204));
        jMenu5.setText("Pin Change");

        jMenuItem7.setText("Pin Change");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("logout");

        jMenuItem8.setText("Log Out");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // Code For MiniStatement
        ministmt.setVisible(true);
         DepositWithdrawl.setVisible(false);
         transferfund.setVisible(false);
         fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // code for deposit and withdrawl
        DepositWithdrawl.setVisible(true);
          ministmt.setVisible(false);
         transferfund.setVisible(false);
         fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Code For TransFer Fund
        transferfund.setVisible(true);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // code For Fast Cash Withdrawl
        fastcashwith.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
         balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // code for balance Enquiry
        balanceEnquiry.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       // code for mobile Registration 
        mobreg.setVisible(true);
        transferfund.setVisible(false);
        ministmt.setVisible(false);
        DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
        pinchange.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // Code for Pin change
        pinchange.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // code For Logout
        new loginWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         // code for deposit and withdrawl
        DepositWithdrawl.setVisible(true);
          ministmt.setVisible(false);
         transferfund.setVisible(false);
         fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         // code For Fast Cash Withdrawl
        fastcashwith.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
         balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 // Code For TransFer Fund
        transferfund.setVisible(true);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       // code for balance Enquiry
        balanceEnquiry.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      // Code For MiniStatement
        ministmt.setVisible(true);
         DepositWithdrawl.setVisible(false);
         transferfund.setVisible(false);
         fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
         pinchange.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // code for mobile Registration 
        mobreg.setVisible(true);
        transferfund.setVisible(false);
        ministmt.setVisible(false);
        DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
        pinchange.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
         // Code for Pin change
        pinchange.setVisible(true);
         transferfund.setVisible(false);
         ministmt.setVisible(false);
         DepositWithdrawl.setVisible(false);
        fastcashwith.setVisible(false);
        balanceEnquiry.setVisible(false);
         mobreg.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // code For Logout
        new loginWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed
java.sql.ResultSet rs;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CODE FOR DEPOSIT
        try{
            String ac_no =jTextField1.getText();
            String amt = jTextField2.getText();
            String ways = jTextField3.getText();
            
            DBConnection db = new DBConnection();
            java.util.Calendar  c= Calendar.getInstance();
            
            db.pstmt = db.con.prepareStatement("insert into transaction(ac_no,amount,ways)values(?,?,?)");
            db.pstmt.setString(1,ac_no);
            db.pstmt.setString(2, amt);
            db.pstmt.setString(3,ways);
            int i = db.pstmt.executeUpdate();
            if(i>0){
                
//               db.pstmt = db.con.prepareStatement("update  user_info set balance =balance+amt where ac_no=?");
//               db.pstmt.setString(1, ac_no);
//                int j = db.pstmt.executeUpdate();
//                if(j>0){
                JOptionPane.showMessageDialog(this,amt +"Deposit Successsul");
//            }
//                else{
//                     JOptionPane.showMessageDialog(this,"Transaction fail"); 
//                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Code For Withdrawl
        try{
          String ac_no = jTextField1.getText();
          String amt= jTextField2.getText();
          String utype = jTextField3.getText();
          
          DBConnection db = new DBConnection();
          db.pstmt = db.con.prepareStatement("insert into user_info(ac_no,amount,ways)values(?,?,?)");
          db.pstmt.setString(1, ac_no);
          db.pstmt.setString(2, amt);
          db.pstmt.setString(3,utype);
          rs = db.pstmt.executeQuery();
          if(rs.next()){
              
            db.pstmt = db.con.prepareStatement("update user_info set balance=balance+amt where ac_no=?");
               db.pstmt.setString(1, ac_no);
              JOptionPane.showMessageDialog(this, amt+"Credited SuccessFull,Your Current Balance is ");
          }
          
          
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Code For reset
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Code for balance Enquiry
        try{
            String ac_no= jTextField9.getText();                    
            DBConnection db = new DBConnection();
            db.pstmt = db.con.prepareStatement("select balance from user_info where ac_no=?");
            db.pstmt.setString(1,ac_no);                     
            rs = db.pstmt.executeQuery();
            if (rs.next()) {
                jLabel29.setText(rs.getString(1));   
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Code for ministatement
        try{
            String ac_no = jTextField12.getText();
              Vector<String> header = new Vector<String>();
           Vector<Vector<String>>data = new Vector<Vector<String>>();
           header.add("Dates");
           header.add("Amount");
           header.add("Ways");
           header.add("Balance");
           
            DBConnection db = new DBConnection();
            db.pstmt = db.con.prepareStatement("select  * from transaction where ac_no=? ");
            db.pstmt.setString(1, ac_no);
            db.rst= db.pstmt.executeQuery();
            
             while(db.rst.next()){
              Vector<String> temp = new Vector<String>();
              temp.add(db.rst.getString(1));
              temp.add(db.rst.getString(2));
              temp.add(db.rst.getString(3));
              temp.add(db.rst.getString(4));
              
              data.add(temp);
             }
             jTable1.setModel(new DefaultTableModel(data,header));
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // Code For Mobile Registration
        try{
            String ac_no = jTextField10.getText();
            String mob = jTextField13.getText();
            
            DBConnection db = new DBConnection();
            db.pstmt = db.con.prepareStatement(" update user_info set phone=? where ac_no=? ");
            db.pstmt.setString(1,mob);
            db.pstmt.setString(2, ac_no);
            int i = db.pstmt.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(this, "Mobile Registered");
            }
            else{
                JOptionPane.showMessageDialog(this, "Mobile Not Registered"); 
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // code for pin change
       try{
           String ac_no = jTextField14.getText();
         String opswd = jPasswordField5.getText();
         
         String npswd = jTextField11.getText();
         String cpswd = jPasswordField6.getText();
         DBConnection db = new DBConnection();
         db.pstmt = db.con.prepareStatement("select * from user_info where ac_no=? and passwd=?");
         db.pstmt.setString(1, ac_no);
         db.pstmt.setString(2,opswd);
         
         db.rst = db.pstmt.executeQuery();
         if(db.rst.next()){
            if(npswd.equals(cpswd)){
                db.pstmt = db.con.prepareStatement("update user_info set passwd=? where ac_no=?");
                db.pstmt.setString(1,npswd);
                db.pstmt.setString(2, ac_no);
                int i= db.pstmt.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(this,"password updated Successfully");
                    
                }
            }
                else{
                    JOptionPane.showMessageDialog(this,"New and Old Password Does Not Match");
                }
            
         }
         else{
             JOptionPane.showMessageDialog(this,"Old Password Does Not Match to :"+ac_no);
         }
         
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame DepositWithdrawl;
    private javax.swing.JInternalFrame balanceEnquiry;
    private javax.swing.JLabel balimg;
    private javax.swing.JLabel bgmob;
    private javax.swing.JInternalFrame fastcashwith;
    private javax.swing.JLabel fastimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame ministmt;
    private javax.swing.JLabel ministmtimg;
    private javax.swing.JInternalFrame mobreg;
    private javax.swing.JInternalFrame pinchange;
    private javax.swing.JLabel pinimg;
    private javax.swing.JInternalFrame transferfund;
    private javax.swing.JLabel transimg;
    private javax.swing.JLabel withimg;
    // End of variables declaration//GEN-END:variables
}
